// Builds the judge/manager-facing "Sprint Pack": a compact, shareable snapshot
// of a run plus a clean Markdown export. Pure + dependency-free so it works
// offline and in the public /share view (no store, no Bob, no backend).

import type { AutoPilotRun } from './types';
import { computeHealth } from './health';

export interface PackFile {
  path: string;
  type: string;
  status: 'approved' | 'deferred' | 'pending';
  lines: number;
  reason?: string;
}

/** Small, URL-safe payload (no full file bodies) — the shareable snapshot. */
export interface ReportSnapshot {
  v: 1;
  repo: string;
  isDemo: boolean;
  grade: string;
  score: number;
  headline: string;
  reasons: string[];
  summary: string;
  files: PackFile[];
  filesAnalyzed: number;
  cost: number;
  prUrl?: string;
  startedAt: number;
  completedAt?: number;
}

export function repoLabel(url: string): string {
  const m = url.match(/github\.com\/([^/]+\/[^/?#]+)/i);
  return m ? m[1].replace(/\.git$/, '') : url;
}

function fileLines(content: string): number {
  return content ? content.split('\n').length : 0;
}

export function buildSnapshot(run: AutoPilotRun): ReportSnapshot {
  const h = computeHealth(run);
  return {
    v: 1,
    repo: run.githubUrl,
    isDemo: run.isDemo,
    grade: h.grade,
    score: h.score,
    headline: h.headline,
    reasons: h.reasons,
    summary: (run.executiveSummary ?? '').trim(),
    files: run.safeWins.map((w) => ({
      path: w.targetPath,
      type: w.type,
      status: w.safetyStatus,
      lines: fileLines(w.content),
      reason: w.safetyReason,
    })),
    filesAnalyzed: run.filesAnalyzed ?? 0,
    cost: run.totalCost ?? 0,
    prUrl: run.prUrl,
    startedAt: run.startedAt,
    completedAt: run.completedAt,
  };
}

function bullets(text: string): string[] {
  return text
    .split('\n')
    .map((l) => l.replace(/^[•\-*]\s*/, '').trim())
    .filter(Boolean);
}

export function snapshotToMarkdown(s: ReportSnapshot): string {
  const approved = s.files.filter((f) => f.status === 'approved');
  const deferred = s.files.filter((f) => f.status === 'deferred');
  const date = new Date(s.completedAt ?? s.startedAt).toISOString().slice(0, 10);

  const lines: string[] = [
    `# Sprint Pack — ${repoLabel(s.repo)}`,
    '',
    `> Generated by **BobSprint** (IBM Bob Hackathon 2026) · ${date}`,
    '',
    `## Health: Grade ${s.grade} (${s.score}/100) — ${s.headline}`,
    '',
    ...s.reasons.map((r) => `- ${r}`),
    '',
    `**Files analyzed:** ${s.filesAnalyzed} · **Bobcoins spent:** ₿${s.cost.toFixed(2)}`,
    '',
  ];

  if (s.summary) {
    lines.push('## Executive summary', '', ...bullets(s.summary).map((b) => `- ${b}`), '');
  }

  lines.push(`## Prioritized actions (${approved.length})`, '');
  if (approved.length) {
    approved.forEach((f) => lines.push(`- [ ] **${f.path}** — add ${f.type.replace('add-', '')} (${f.lines} lines, Bob-written, safety-approved)`));
  } else {
    lines.push('_No auto-approved changes._');
  }
  lines.push('');

  if (deferred.length) {
    lines.push(`## Deferred for human review (${deferred.length})`, '');
    deferred.forEach((f) => lines.push(`- **${f.path}** — ${f.reason ?? 'flagged by the safety gate'}`));
    lines.push('');
  }

  if (s.prUrl) lines.push(`## Pull request`, '', `Draft PR: ${s.prUrl}`, '');

  lines.push('---', '', '_All changes are additive and were validated by a Bob safety gate before apply._');
  return lines.join('\n');
}
